### ISSUE TITLE
can't seem to find the config files

### ISSUE THREAD

**Issue by banchiebanchie** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#10]
apologies, i dont know if this counts as a bug but im not sure where else to ask

i'd like to go into the config files and mess around with the fae origin. but i cant seem to find them anywhere. am i looking in the wrong place? ive looked both server and clientside. Im playing in 1.18.2 (forge 40.1.0) and im not inclined to change the version due to the whole server thing

**Comment by Aiko-Suzuki** [comment]
There’s no config file if you wanna edit something right click on the jar and open like you would for a zip/rar file.
