### ISSUE TITLE
[BUG] Potion effects (haste, blindness, night vision) don't apply consistently on Dwarf origin

### ISSUE THREAD

**Issue by DestinyPlayer** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#11]
**Describe the bug**
Basically, when I just get the Dwarf origin, or when I respawn, these effects don't seem to apply, and then at some indeterminate point in the game they suddenly appear. And then disappear again if I die.

**To Reproduce**
Unfortunately I have no idea how to reproduce it, as I have no idea what even causes it. So I guess "pick the Dwarf origin, then see if the effects apply or not" would work?

**Expected behavior**
I would expect the effects to apply whenever I respawn.

**Screenshots**
https://prnt.sc/e_r7BoucmZa3
https://prnt.sc/usx3LUqhV9Ht

**Additional context**
Modpack - https://prnt.sc/TUEUgmG_15AJ
Forge - 40.1.52

**Comment by Aiko-Suzuki** [comment]
that's kinda weird the dwarf is the only origin i play can you export your curseforge profile and send it here ?

**Comment by DestinyPlayer** [comment]
https://www.dropbox.com/s/vzc722sl0p5u0fx/Dwaria.zip?dl=0
Here it is.

**Comment by Aiko-Suzuki** [comment]
gona check that tommorow thx

**Comment by Aiko-Suzuki** [comment]
so from what i found it does not seems to be a bug from us. while trying to load your profile i get multiple warning of incompatibilty. Your pekhui version is incompatible with forge 1.18.2 you took the 1.19 version and somehow when giving myself a item in your world i get it twice. could you try to remake your modpack on curseforge ?

**Comment by DestinyPlayer** [comment]
Well, fixing the version of Pehkui and updating your collection seems to have worked. Whenever I press O I have "You can not have any Origins" but when I set it via a GUI it applies everything so now it's working, if weirdly?

**Comment by Aiko-Suzuki** [comment]
the "You can not have any Origins" is a know bug of Origin Forge. for the movement speed i think its from the pekhui scaling that we use for setting the dawrf size

**Comment by DestinyPlayer** [comment]
Apparently I have to reapply the origin whenever I restart the game, but otherwise it seems to be working fine now.
