### ISSUE TITLE
[BUG] No levitation ability for Fae

### ISSUE THREAD

**Issue by Pandaw15** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#13]
The Fae origin doesn't have any ability. The levitation should have been added back apparently, but in game it is not. When choosing the origin there is no Flight category or any ability marker.

1. With an orb, go to Fae and choose it
2. Try to levitate using the primary ability

We should have been able to levitate using the primary ability, but nothing happens.

![image](https://user-images.githubusercontent.com/82103549/178151791-3c85ef1f-ace6-4827-9994-e4fdc2dd0986.png)
![image](https://user-images.githubusercontent.com/82103549/178151804-3e5347f9-3ad3-4c86-870e-bc508288afe3.png)
![image](https://user-images.githubusercontent.com/82103549/178151827-4281d708-c8ad-40db-a3ad-70abee034bb3.png)
![image](https://user-images.githubusercontent.com/82103549/178151837-30c5c50d-9155-478b-ba34-9a57a6b3465b.png)

I tried other origins and their ability work, so it IS a Fae problem. Maybe the changes done to fix the creative fly haven't been saved or there is an error ?
The mod version is 1.0.10
Pehkui is 3.3.2 for 1.18.2

**Comment by Aiko-Suzuki** [comment]
Sorry for not answering this sooner but we don't even know why its not working pretty sure we just reverted back on what we where using in the 1.16.5 version for levitation :/

**Comment by Pandaw15** [comment]
Maybe the code doesn't work anymore in 1.18, or a spelling error makes the class not load, idk.

**Comment by Aiko-Suzuki** [comment]
could you try with latest version (1.1.2)

**Comment by Pandaw15** [comment]
I updated my modpack in the past few days and now the levitation does "work".
The player does levitate but they fall after some time. In 1.16, we could levitate forever, though slowly as now, but we could. Now it's really annoying to levitate for 10s slowly and then fall again and have to retry, or try to quicky reactivate it while in midair.

**Comment by Arkwys** [comment]
Forgot to comment on this issue, an update we did a while ago should made the levitation time as it was before other changes.
