### ISSUE TITLE
[BUG] Race correlated effects are cleared

### ISSUE THREAD

**Issue by igorosky** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#16]
**Describe the bug**
When play as siren, dwarf (probably there is few more) can't get effects that are somehow correlated to the race.
E.g. siren gets regeneration, night vision and dolphine grace when in water, but when one of these effects is given by potion or command it disappears after few moments (probably one game tick).

**To Reproduce**
1. Play as Siren
2. Use nigh vision potion (outside water)

**Expected behavior**
When effect is given by other source than race interaction it should not be cleared or overrited by race effect. Probably good solution would be to create separate effects for reaces.

**Edit**
Game version 1.16.5
Forge - 36.2.34
Mod - 1.1.3
Singleplayer

**Comment by Arkwys** [comment]
@igorosky On what version are you on, are you in a server or in singleplayer?

**Comment by muon-rw** [comment]
This is a bug related to Origins Forge's implementation of `block_in_radius`. Report the bug to Origins Forge - alternatively, the block radius check could be lowered significantly which should fix the FPS drop at the expense of some power functionality.
