### ISSUE TITLE
[BUG] Selecting Origin Doesn't Work (Version 1.18.x)

### ISSUE THREAD

**Issue by zugdraus** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#18]
(1.18) it is not a crash or something like that its just that as soon as i pick knight or any other origin without any powers it just says you have not picked a origin

**Comment by Arkwys** [comment]
@zugdraus Are you on a server or in singleplayer? If you are on a server does everyone have the same glitch?
