### ISSUE TITLE
[BUG] Minotaur cant wear upper body armor

### ISSUE THREAD

**Issue by DrDonutella** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#2]
**Minotaur cannot wear any armor**
The minotaur cannot wear chest and helmet armor

**To Reproduce**
1. Go to any game
2. You can't use armor 

**Expected behavior**
The minotaur should be able to wear chest and helmet and unable to wear leggings and boots

**Comment by Aiko-Suzuki** [comment]
Fixed in [Collection of Singiro 1.18.x-1.0.7](https://www.curseforge.com/minecraft/mc-mods/collection-of-singiro/files/3769352)
