### ISSUE TITLE
me and my friends are using this mod on a small modded server and are having issues with the minotaur origin.

### ISSUE THREAD

**Issue by SkyBearer4606** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#21]
me and my friends are using this mod in a small modded origins server and we are having issues with the minotaur origin. the minotaur origin is unable to hit entities and we have already tried multiple fixes for it like adjusting scale with the pehkui mod. If possible i'd like to know why this is happening so i can fix it. thank you for your time!

**Comment by Arkwys** [comment]
@SkyBearer4606 What version are you using and what other mods do you have on your Modded Origins Server?
