### ISSUE TITLE
[BUG] Yeti class features not working

### ISSUE THREAD

**Issue by AsingleBadCat** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#23]
My friends and I have made a small 1.19.2 modded world,

To reproduce the bug, is just select yeti

My ability to shoot ice via [Frigid Pulse] does not work. I've tried rebinding it, and still nothing.
The feature [Winter Body] which increases my size also does not work. 

Are these issue due to a missing mod I didnt see? or are these simply bugs

I'll attach a screenshot of the current mods in the pack. Please if there is something I have forgotten, or if there is conflicting mods, I'm hear to listen
![image](https://user-images.githubusercontent.com/124025920/215682363-54e6889d-25a4-4fab-9dca-5e7096c2d64c.png)

**Comment by Aiko-Suzuki** [comment]
Really sorry about this but i lately do not work as much on this project since I don't have time.

I know that in the pass those type of problem came from origin forge. the way i got it working most of the time is by trying a previous version until i found one working. 😅

**Comment by AsingleBadCat** [comment]
Sadly going back in version would corrupt the world, as we have been using blocks and other items from the newer version. Is there any other suggested fixes you could tell me? or is it possible to find the code for both the size and the ice shooting ability? either or would be great. I just see it unfair to have the yetis buffs without the size de-buff.

Also thank you for the quick response :)
