### ISSUE TITLE
[BUG] Significant FPS drop when selecting moth origin

### ISSUE THREAD

**Issue by Dangermad** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#26]
On version 1.19.2, when selecting the moth origin, there is a significant drop in fps

I am using Medieval MC

Human FPS
![image](https://user-images.githubusercontent.com/59689123/232957074-17d31e95-d322-40d8-861a-dd671d698b13.png)
Moth FPS
![image](https://user-images.githubusercontent.com/59689123/232957265-db035448-c9dc-49bc-8c8c-21d7b0cd05c5.png)

Highly saddening, I just wanna be a moth

**Comment by Dangermad** [comment]
I've done some trial and error myself, this is definitely caused by the various light affinities

**Comment by Dangermad** [comment]
my solution has been to make a version for personal use that strips it down to the base lamp affinity, fps back to normal

**Comment by DiademDracon** [comment]
I don't see a 1.19.2 version on Forge, which one works for it?

**Comment by Dangermad** [comment]
oh wow I hadn't even noticed that, I seem to have found it on 9minecraft

**Comment by Arkwys** [comment]
@Dangermad Have you tried it in 1.19.4 ? Does the bug still persist in newer versions?
