### ISSUE TITLE
Game crashes when on fire with siren origin[BUG]

### ISSUE THREAD

**Issue by DarkRnight** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#3]
**Describe the bug**
When catching fire while having the Siren origin, the game crashes. On a server you'll get kicked and see "Internal server error" message.

**To Reproduce**
1. Start a world and select the siren origin.
2. Get a flint and steel or find any other source that sets the player on fire.
3. Make sure you're in survival and set the player on fire.

**Expected behavior**
The player dies as the Siren origin normally instantly kills the player when in contact with fire.

Video:
https://user-images.githubusercontent.com/65226786/165180234-d6790cd4-1d2c-4b33-a3ff-e0a1f5890d28.mov

Crashreport:
[crash-2022-04-25_23.21.49-server.txt]
https://github.com/Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues/files/8558221/crash-2022-04-25_23.21.49-server.txt

**Comment by Aiko-Suzuki** [comment]
sadly enough that may be an [origin ](https://www.curseforge.com/minecraft/mc-mods/origins-forge) bug since we straight up use [Damage entity_action](https://origins.readthedocs.io/en/latest/types/entity_action_types/damage/) with [self_action_on_hit](https://origins.readthedocs.io/en/latest/types/power_types/self_action_on_hit/) to kill the player. and we use [damage_condition](https://origins.readthedocs.io/en/latest/types/damage_condition_types/fire/) to check if the player took fire damage.

if it's not an origin bug just respond gonna look more at it.

**Comment by DarkRnight** [comment]
I'll open an issue on the Origin Forge page but the system does work on the fabric version. I don't know in what ways they're different or if it tells you anything but I thought I'd mention it.

**Comment by EdwinMindcraft** [comment]
It's a dumb forge issue. Long story short:
When player takes fire damage, the mod deals a 99 fire damage to the player.
And since the player just took fire damage, the cycle repeats.
I might have a misplaced hook. I'll look into it.

**Comment by DarkRnight** [comment]
Hi @EdwinMindcraft 
I'm sorry, I don't want to sound pushy but have you found anything yet? I don't know how much time you have but I'd like to play on a server with my friends but I don't want to crash all the time. Do you think the issue will be resolved quickly or does Forge or maybe the Origin Forge authors need to do something about the issue? Let me know and thanks for taking a look!

**Comment by Aiko-Suzuki** [comment]
gonna make some changes next Monday to try and fix it.

**Comment by Aiko-Suzuki** [comment]
well after a couple of tries, i cannot seem to make it work with modify_damage_taken.

```json
{
    "type": "origins:modify_damage_taken",
    "damage_condition": {
        "type": "origins:fire"
    },
    "modifier": {
        "name": "Flammable",
        "operation": "addition",
        "value": 99
    }
}
```

**Comment by Aiko-Suzuki** [comment]
If anyone has a idea to fix it you are welcome to share your thoughts

**Comment by DarkRnight** [comment]
So are the differences in code between the forge and fabric version only because of the two different loaders?
As far as I could find this is what runs on the fabric version:

{
	"type": "origins:self_action_when_hit",
	"entity_action": {
		"type": "origins:damage",
		"amount": 99,
		"source": {
			"name": "onFire",
			"fire": true,
			"bypasses_armor": true
		}
	},
	"cooldown": 20,
	"damage_condition": {
		"type": "origins:fire"
	}
}

I have a very limited amount of coding knowledge but why is the code here different? It has a cooldown and a different type

**Comment by DarkRnight** [comment]
I also don't know how to share code like you did so I just copypasted it.

**Comment by Aiko-Suzuki** [comment]
Well that what i was using originally but it cause the crash on forge

**Comment by Aiko-Suzuki** [comment]
so i found a away to fix it but 2 death msg appear in chat :/

**Comment by Aiko-Suzuki** [comment]
gonna be in next update : https://www.curseforge.com/minecraft/mc-mods/collection-of-singiro/files/3812420 (waiting for review)
