### ISSUE TITLE
Removed Regen and Levitation for the Fae Origin 

### ISSUE THREAD

**Issue by zoinksinmyyoinks** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#4]
The original medieval origin for the Fae included a levitation ability activated with G, and a regen ability that used hunger and was activated with R. the new origins description for the fae does not include either of those things, and the keys to activate these primary/secondary powers do not do anything. it seems like neither of these abilities are included in this version, or i’m just dumb and missed something.

**Comment by Aiko-Suzuki** [comment]
well in the files both abilities are still there's  🙁.
if you check yourself by right-clicking the jar and opening it with WinRAR or 7zip.

**Comment by Aiko-Suzuki** [comment]
are you on 1.18.2 or 1.16.5 ?

**Comment by Aiko-Suzuki** [comment]
Am gonna try to check if a origin update did some breaking change.

**Comment by Arkwys** [comment]
Fixed In Newest Update!

**Comment by Aiko-Suzuki** [comment]
fixed in last update now with creative flight.

**Comment by Aiko-Suzuki** [comment]
@Arkwys fat

**Comment by Arkwys** [comment]
@Aiko-Suzuki FAT
