### ISSUE TITLE
Werewolf race's strength and health buff is given at low light levels, regardless of time[BUG]

### ISSUE THREAD

**Issue by CodyTheHunter** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#6]
**Describe the bug**
I get health boost and strength if I'm in the shade, and when it's night time.

**To Reproduce**
Step under any ceiling; this includes leaves.

**Expected behavior**
I shouldn't get a buff in the shade. I should only get this buff at nighttime.

**Screenshots**
[https://drive.google.com/file/d/1f_MTgF2MHcCFoeiBuWvSnVeAwFkwhv_U/view?usp=sharing](url)

**Additional context**
None lol

**Comment by Aiko-Suzuki** [comment]
Gonna look into it when my eye injury gonna be healed.

**Comment by Aiko-Suzuki** [comment]
fixed in https://www.curseforge.com/minecraft/mc-mods/collection-of-singiro/files/3812420 (file waiting for review)
