### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kaye-Potassium** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#7]
**Describe the bug**
Scaling height resets to default but width remains the same after death

**To Reproduce**
1. Download updated version of the mod (went from 1.0.7 to 1.0.9)
2. Launch game
3. Choose dwarf origin
4. Die and Respawn
5. Height returns to normal but width stays the same

**Expected behavior**
When I die and respawn, I expect the scaling to stay small and wide.

**Screenshots**
https://www.youtube.com/watch?v=WkI2L1gQ9Po

**Additional context**
Mods Used (Forge):
- Epic Knights Armour
- Alcocraft
- Alex's Mobs
- Appleskin
- Applied Energistics 2
- Aquaculture
- Architectury
- Ars Nouveau
- AutoRegLib
- Balm
- Biomes O Plenty
- Stone Blocky Doors
- Caeulus
- Crayfish Furniture
- Chipped
- Citadel
- Clumps
- Collection of Singiro
- Cooking for Blockheads
- Cosmetic Armour Reworked
- Create
- Create Stuff Additions 
- Curios 
- Custom Player Models
- Decorative Blocks 
- Domum Ornamentum
- DPAnvil
- Elementalcraft
- Endermail
- Every Compat
- Fakename
- Farmer's Delight
- Fast Leaf Decay
- Flywheel 
- Geckolib
- Goblin Traders
- Guide API VP
- Jade
- JEI
- Just Needed
- Lootr
- Magnum Torch
- Macaw's Bridges, Fences, Furniture, Paintings, Windows
- Mysterious Mountain
- More Villagers
- Neat
- Optifine
- Origins
- Origins Classes
- Paraglider
- Patchouli
- Pehkui
- PuzzlesLib
- Quark
- Quick Teleports
- Selene
- Serene Season
- Supplementaries
- TerraBlender 
- U Team Core
- Useful Backpacks
- Vampires Need Umbrellas
- Vampirism
- Waystones
- Werewolves
- Worldedit 
- Xaero's Minimap and Worldmap
- XP Tome

**Comment by Aiko-Suzuki** [comment]
the nitwit class seems to conflict with the dwarf. 😕
i cannot reproduce with the [Collection Of Singiro - Test profile](https://github.com/Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues/files/8934591/Collection.Of.Singiro.-.Test.profile-1.zip)

**Comment by Aiko-Suzuki** [comment]
could you send your curse forge profile?

**Comment by Aiko-Suzuki** [comment]
Sorry gona close this for inactivity
